name: currency

services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8000:8000
    depends_on:
      database:
          condition: service_healthy
    networks:
      - app-network

  database:
    container_name: database
    image: mysql:9.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: strcarne
      MYSQL_PASSWORD: ilovegolang
      MYSQL_DATABASE: currency
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
