// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Get general service info and check if service is up and running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Returns general service info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_strCarne_currency_pkg_shared.Response-github_com_strCarne_currency_pkg_models_ProjectInfo"
                        }
                    }
                }
            }
        },
        "/rates/all-collected": {
            "get": {
                "description": "Get all rates, that have been ever polled from NBRB's API and stored into the database. Can return 500 in\ncase if DB is not reachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rates"
                ],
                "summary": "Returns all collected rates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_strCarne_currency_pkg_shared.Response-array_github_com_strCarne_currency_internal_schema_Rate"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_strCarne_currency_pkg_shared.Response-error"
                        }
                    }
                }
            }
        },
        "/rates/by-date/{date}": {
            "get": {
                "description": "Get all rates on specified date and store them into the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rates"
                ],
                "summary": "Returns rates on specified date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "date in format yyyy-mm-dd",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_strCarne_currency_pkg_shared.Response-array_github_com_strCarne_currency_internal_schema_Rate"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_strCarne_currency_pkg_shared.Response-error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_strCarne_currency_internal_schema.Rate": {
            "type": "object",
            "properties": {
                "Cur_Abbreviation": {
                    "type": "string"
                },
                "Cur_ID": {
                    "type": "integer"
                },
                "Cur_Name": {
                    "type": "string"
                },
                "Cur_OfficialRate": {
                    "type": "number"
                },
                "Cur_Scale": {
                    "type": "integer"
                },
                "Date": {
                    "type": "string"
                }
            }
        },
        "github_com_strCarne_currency_pkg_models.ProjectInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "version": {
                    "$ref": "#/definitions/github_com_strCarne_currency_pkg_models.Version"
                }
            }
        },
        "github_com_strCarne_currency_pkg_models.Version": {
            "type": "object",
            "properties": {
                "major": {
                    "type": "integer"
                },
                "minor": {
                    "type": "integer"
                },
                "patch": {
                    "type": "integer"
                }
            }
        },
        "github_com_strCarne_currency_pkg_shared.Response-array_github_com_strCarne_currency_internal_schema_Rate": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_strCarne_currency_internal_schema.Rate"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_strCarne_currency_pkg_shared.Response-error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_strCarne_currency_pkg_shared.Response-github_com_strCarne_currency_pkg_models_ProjectInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_strCarne_currency_pkg_models.ProjectInfo"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "0.0.0.0:8000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Currency",
	Description:      "Service collects all conversion rates relative to BYN from NBRB's API once a day.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
